// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'guardianControls': string;
  'playerControls': string;
  'ui': string;
}
export const cssExports: CssExports;
export default cssExports;
