name: bricks-runner-impulse-game
on:
  push:
    branches: [ bricks-runner-impulse-game ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  app-bricks-impulse-12-2023:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bricks-runner-impulse-game
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache NPM dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      
      - name: Install dependencies
        id: Npm-install
        run: npm install

      - name: Build project
        id: Project-build
        run: npm run build

      - name: Deploy application to GHP /ponomarenko-alex-otus/bricks-runner/impulse/game 🚀
        id: Deploy-app
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: bricks-runner-impulse-game/temp/ui-dist  # The folder the action should deploy.
          TARGET_FOLDER: impulse/game
          CLEAN: true # Automatically remove deleted files from the deploy branch
